steps:
- id: 'tf init'
  name: 'hashicorp/terraform:0.12.26'
  entrypoint: 'sh'
  args: 
  - '-c'
  - |
      terraform init
      

# [START tf-plan]
- id: 'tf plan'
  name: 'hashicorp/terraform:0.12.26'
  entrypoint: 'sh'
  args: 
  - '-c'
  - | 
      terraform plan
 
